from distutils.core import setup, Extension
from Cython.Build import cythonize
import numpy as np

# setup(
#         ext_modules = cythonize([
#             Extension(
#                 "wrapper",
#                 sources=["wrapper.pyx"],
#                 language="c++",
#                 extra_link_args=["-fopenmp"],
#                 extra_compile_args=["-DGENERICIO_NO_MPI"],
#                 extra_objects=[
#                     "./frontend/GenericIO.o",
#                     "./frontend/thirdparty/blosc/blosc.o",
#                     "./frontend/thirdparty/blosc/blosclz.o",
#                     "./frontend/thirdparty/blosc/shuffle.o",
#                     "./frontend/thirdparty/blosc/bitshuffle-generic.o",
#                     "./frontend/thirdparty/blosc/shuffle-generic.o",
#                     "./frontend/thirdparty/blosc/internal-complibs/zlib-1.2.8/gzwrite.o",
#                     "./frontend/thirdparty/blosc/internal-complibs/zlib-1.2.8/crc32.o",
#                     "./frontend/thirdparty/blosc/internal-complibs/zlib-1.2.8/inffast.o",
#                     "./frontend/thirdparty/blosc/internal-complibs/zlib-1.2.8/zutil.o",
#                     "./frontend/thirdparty/blosc/internal-complibs/zlib-1.2.8/infback.o",
#                     "./frontend/thirdparty/blosc/internal-complibs/zlib-1.2.8/deflate.o",
#                     "./frontend/thirdparty/blosc/internal-complibs/zlib-1.2.8/inflate.o",
#                     "./frontend/thirdparty/blosc/internal-complibs/zlib-1.2.8/gzread.o",
#                     "./frontend/thirdparty/blosc/internal-complibs/zlib-1.2.8/gzlib.o",
#                     "./frontend/thirdparty/blosc/internal-complibs/zlib-1.2.8/gzclose.o",
#                     "./frontend/thirdparty/blosc/internal-complibs/zlib-1.2.8/uncompr.o",
#                     "./frontend/thirdparty/blosc/internal-complibs/zlib-1.2.8/compress.o",
#                     "./frontend/thirdparty/blosc/internal-complibs/zlib-1.2.8/inftrees.o",
#                     "./frontend/thirdparty/blosc/internal-complibs/zlib-1.2.8/trees.o",
#                     "./frontend/thirdparty/blosc/internal-complibs/zlib-1.2.8/adler32.o",
#                     "./frontend/thirdparty/blosc/internal-complibs/lz4-1.7.2/lz4.o",
#                     "./frontend/thirdparty/blosc/internal-complibs/lz4-1.7.2/lz4hc.o",
#                     "./frontend/thirdparty/blosc/internal-complibs/zstd-0.7.4/legacy/zstd_v01.o",
#                     "./frontend/thirdparty/blosc/internal-complibs/zstd-0.7.4/legacy/zstd_v02.o",
#                     "./frontend/thirdparty/blosc/internal-complibs/zstd-0.7.4/legacy/zstd_v03.o",
#                     "./frontend/thirdparty/blosc/internal-complibs/zstd-0.7.4/legacy/zstd_v06.o",
#                     "./frontend/thirdparty/blosc/internal-complibs/zstd-0.7.4/legacy/zstd_v04.o",
#                     "./frontend/thirdparty/blosc/internal-complibs/zstd-0.7.4/legacy/zstd_v05.o",
#                     "./frontend/thirdparty/blosc/internal-complibs/zstd-0.7.4/compress/fse_compress.o",
#                     "./frontend/thirdparty/blosc/internal-complibs/zstd-0.7.4/compress/zstd_compress.o",
#                     "./frontend/thirdparty/blosc/internal-complibs/zstd-0.7.4/compress/huf_compress.o",
#                     "./frontend/thirdparty/blosc/internal-complibs/zstd-0.7.4/compress/zbuff_compress.o",
#                     "./frontend/thirdparty/blosc/internal-complibs/zstd-0.7.4/common/entropy_common.o",
#                     "./frontend/thirdparty/blosc/internal-complibs/zstd-0.7.4/common/xxhash.o",
#                     "./frontend/thirdparty/blosc/internal-complibs/zstd-0.7.4/common/zstd_common.o",
#                     "./frontend/thirdparty/blosc/internal-complibs/zstd-0.7.4/common/fse_decompress.o",
#                     "./frontend/thirdparty/blosc/internal-complibs/zstd-0.7.4/dictBuilder/zdict.o",
#                     "./frontend/thirdparty/blosc/internal-complibs/zstd-0.7.4/dictBuilder/divsufsort.o",
#                     "./frontend/thirdparty/blosc/internal-complibs/zstd-0.7.4/decompress/zstd_decompress.o",
#                     "./frontend/thirdparty/blosc/internal-complibs/zstd-0.7.4/decompress/huf_decompress.o",
#                     "./frontend/thirdparty/blosc/internal-complibs/zstd-0.7.4/decompress/zbuff_decompress.o",
#                     "./frontend/thirdparty/blosc/internal-complibs/snappy-1.1.1/snappy-c.o",
#                     "./frontend/thirdparty/blosc/internal-complibs/snappy-1.1.1/snappy.o",
#                     "./frontend/thirdparty/blosc/internal-complibs/snappy-1.1.1/snappy-sinksource.o",
#                     "./frontend/thirdparty/blosc/internal-complibs/snappy-1.1.1/snappy-stubs-internal.o",
#                 ],
#             ),
#         ]),
#         include_dirs = [
#                 np.get_include(),
#         ]
# )

import os
os.environ["CXX"] = "mpicxx"
setup(
        ext_modules = cythonize([
            Extension(
                "mpi_wrapper",
                sources=["wrapper.pyx"],
                language="c++",
                extra_link_args=["-fopenmp", "-L/usr/lib64/openmpi/lib/" "-lmpi"],
                extra_objects=[
                    "./mpi/GenericIO.o",
                    "./mpi/thirdparty/blosc/blosc.o",
                    "./mpi/thirdparty/blosc/blosclz.o",
                    "./mpi/thirdparty/blosc/shuffle.o",
                    "./mpi/thirdparty/blosc/bitshuffle-generic.o",
                    "./mpi/thirdparty/blosc/shuffle-generic.o",
                    "./mpi/thirdparty/blosc/internal-complibs/zlib-1.2.8/gzwrite.o",
                    "./mpi/thirdparty/blosc/internal-complibs/zlib-1.2.8/crc32.o",
                    "./mpi/thirdparty/blosc/internal-complibs/zlib-1.2.8/inffast.o",
                    "./mpi/thirdparty/blosc/internal-complibs/zlib-1.2.8/zutil.o",
                    "./mpi/thirdparty/blosc/internal-complibs/zlib-1.2.8/infback.o",
                    "./mpi/thirdparty/blosc/internal-complibs/zlib-1.2.8/deflate.o",
                    "./mpi/thirdparty/blosc/internal-complibs/zlib-1.2.8/inflate.o",
                    "./mpi/thirdparty/blosc/internal-complibs/zlib-1.2.8/gzread.o",
                    "./mpi/thirdparty/blosc/internal-complibs/zlib-1.2.8/gzlib.o",
                    "./mpi/thirdparty/blosc/internal-complibs/zlib-1.2.8/gzclose.o",
                    "./mpi/thirdparty/blosc/internal-complibs/zlib-1.2.8/uncompr.o",
                    "./mpi/thirdparty/blosc/internal-complibs/zlib-1.2.8/compress.o",
                    "./mpi/thirdparty/blosc/internal-complibs/zlib-1.2.8/inftrees.o",
                    "./mpi/thirdparty/blosc/internal-complibs/zlib-1.2.8/trees.o",
                    "./mpi/thirdparty/blosc/internal-complibs/zlib-1.2.8/adler32.o",
                    "./mpi/thirdparty/blosc/internal-complibs/lz4-1.7.2/lz4.o",
                    "./mpi/thirdparty/blosc/internal-complibs/lz4-1.7.2/lz4hc.o",
                    "./mpi/thirdparty/blosc/internal-complibs/zstd-0.7.4/legacy/zstd_v01.o",
                    "./mpi/thirdparty/blosc/internal-complibs/zstd-0.7.4/legacy/zstd_v02.o",
                    "./mpi/thirdparty/blosc/internal-complibs/zstd-0.7.4/legacy/zstd_v03.o",
                    "./mpi/thirdparty/blosc/internal-complibs/zstd-0.7.4/legacy/zstd_v06.o",
                    "./mpi/thirdparty/blosc/internal-complibs/zstd-0.7.4/legacy/zstd_v04.o",
                    "./mpi/thirdparty/blosc/internal-complibs/zstd-0.7.4/legacy/zstd_v05.o",
                    "./mpi/thirdparty/blosc/internal-complibs/zstd-0.7.4/compress/fse_compress.o",
                    "./mpi/thirdparty/blosc/internal-complibs/zstd-0.7.4/compress/zstd_compress.o",
                    "./mpi/thirdparty/blosc/internal-complibs/zstd-0.7.4/compress/huf_compress.o",
                    "./mpi/thirdparty/blosc/internal-complibs/zstd-0.7.4/compress/zbuff_compress.o",
                    "./mpi/thirdparty/blosc/internal-complibs/zstd-0.7.4/common/entropy_common.o",
                    "./mpi/thirdparty/blosc/internal-complibs/zstd-0.7.4/common/xxhash.o",
                    "./mpi/thirdparty/blosc/internal-complibs/zstd-0.7.4/common/zstd_common.o",
                    "./mpi/thirdparty/blosc/internal-complibs/zstd-0.7.4/common/fse_decompress.o",
                    "./mpi/thirdparty/blosc/internal-complibs/zstd-0.7.4/dictBuilder/zdict.o",
                    "./mpi/thirdparty/blosc/internal-complibs/zstd-0.7.4/dictBuilder/divsufsort.o",
                    "./mpi/thirdparty/blosc/internal-complibs/zstd-0.7.4/decompress/zstd_decompress.o",
                    "./mpi/thirdparty/blosc/internal-complibs/zstd-0.7.4/decompress/huf_decompress.o",
                    "./mpi/thirdparty/blosc/internal-complibs/zstd-0.7.4/decompress/zbuff_decompress.o",
                    "./mpi/thirdparty/blosc/internal-complibs/snappy-1.1.1/snappy-c.o",
                    "./mpi/thirdparty/blosc/internal-complibs/snappy-1.1.1/snappy.o",
                    "./mpi/thirdparty/blosc/internal-complibs/snappy-1.1.1/snappy-sinksource.o",
                    "./mpi/thirdparty/blosc/internal-complibs/snappy-1.1.1/snappy-stubs-internal.o",
                ],
            ),
        ]),
        include_dirs = [
                np.get_include(),
                "/usr/include/openmpi-x86_64/"
        ]
)

# python setup.py build_ext --inplace
